# Generated by Django 2.0.9 on 2018-11-15 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('test', 'test1'), ('test0', 'test2'))},
        ),
    ]
